services:
  master_db:
    image: linuxserver/openssh-server
    container_name: host01
    hostname: master
    environment:
      - USER_NAME=ansible
      - USER_PASSWORD=ansible
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
      - PUBLIC_KEY=${PUBLIC_KEY}
    ports:
      - "2224:2222"
      - "5434:5432"
    volumes:
      - ../../.ssh/host01:/config/ssh_host_keys
    restart: unless-stopped
    entrypoint: >
      sh -c "apk add --no-cache python3 && exec /init"

  replica_db:
    image: linuxserver/openssh-server
    container_name: host02
    hostname: replica
    environment:
      - USER_NAME=ansible
      - USER_PASSWORD=ansible
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
      - PUBLIC_KEY=${PUBLIC_KEY}
    ports:
      - "2223:2222"
      - "5435:5432"
    volumes:
      - ../../.ssh/host02:/config/ssh_host_keys
    restart: unless-stopped
    entrypoint: >
      sh -c "apk add --no-cache python3 && exec /init"

  bot_host:
    image: linuxserver/openssh-server
    container_name: host03
    hostname: bot
    network_mode: host
    environment:
      - USER_NAME=ansible
      - USER_PASSWORD=ansible
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
      - PUBLIC_KEY=${PUBLIC_KEY}
    ports:
      - "2225:2222"
    volumes:
      - ../../.ssh/host03:/config/ssh_host_keys
    restart: unless-stopped
    entrypoint: >
      sh -c "apk add --no-cache python3 && exec /init"
